<?php

namespace dashboard\modules\post\models;

use dashboard\modules\user\models\User;
use Yii;


class Category extends \common\models\Category
{
    public function beforeValidate()
    {
        $this->created_by = Yii::$app->user->id;
        return parent::beforeValidate(); // TODO: Change the autogenerated stub
    }
}
